name: TeaksTweaks
version: ${version}
main: me.teakivy.teakstweaks.TeaksTweaks
description: 150+ Toggleable Tweaks & Features including Vanilla Tweaks as a plugin, and more!
api-version: 1.21.7
bootstrapper: me.teakivy.teakstweaks.TeaksTweaksBootstrap